<?xml version="1.0" encoding="utf-8"?><Database Name="CoalPark" Class="CoalParkDataClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-32EVP44\SQLEXPRESS;Initial Catalog=CoalPark;User ID=Ruben" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="CoalParkConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DRIVER" Member="DRIVER">
    <Type Name="DRIVER">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SurName" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ImagePath" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="BirthDay" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TRUCK" Member="TRUCK">
    <Type Name="TRUCK">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TruckID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Plate" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AllowedEntry" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="DriverID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ENTRIES" Member="ENTRIES">
    <Type Name="ENTRIES">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TuckID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EntryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExitDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Weight(Kg)]" Member="Weight_Kg_" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>