<?xml version="1.0" encoding="utf-8"?><Database Name="Rub" Class="DataClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-32EVP44\SQLEXPRESS;Initial Catalog=Rub;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="RubConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.company" Member="company">
    <Type Name="company">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="createdat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.truck" Member="truck">
    <Type Name="truck">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="createdat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="plate" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="model" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="allowed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="company_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.driver" Member="driver">
    <Type Name="driver">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="createdat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="surname" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="birth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="company_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.entries" Member="entries">
    <Type Name="entries">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="createdat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="driver_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="truck_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="company_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="entry_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="entry_weight" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="is_exit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>